CREATE TABLE IF NOT EXISTS tags (
  id INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(100) UNIQUE NOT NULL,
  count INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS bookmarks (
  description VARCHAR(100) NOT NULL,
  extended VARCHAR(100),
  hash VARCHAR(32) PRIMARY KEY UNIQUE NOT NULL, /* md5-hash */
  href VARCHAR(100) NOT NULL,
  meta VARCHAR(100),
  shared BOOLEAN NOT NULL,
  tags VARCHAR(255),
  time DATETIME NOT NULL,
  toread BOOLEAN NOT NULL
);
