const ICLOUD_DEFAULT_DIRECTORY_NAME = 'Pinbored'
const LANDING_ROUTE_AFTER_LOGIN = 'bookmarks'
const BOOKMARKS_PAGE_DEFAULT_PAGE_SIZE = 9
const STALE_CHECKER_DEFAULT_CONCURRENCY = 4
const ACTION_DEBOUNCE_TIME = 1000

export {
  LANDING_ROUTE_AFTER_LOGIN,
  BOOKMARKS_PAGE_DEFAULT_PAGE_SIZE,
  STALE_CHECKER_DEFAULT_CONCURRENCY,
  ACTION_DEBOUNCE_TIME,
  ICLOUD_DEFAULT_DIRECTORY_NAME,
}
