name: build

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    if: '!cancelled()'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.8
        with:
          version: 11.3.0
          cache: true
      - run: pnpm install
      - run: pnpm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.8
        with:
          version: 11.3.0
          cache: true
      - run: pnpm run test

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.8
        with:
          version: 11.3.0
          cache: true
      - run: pnpm run lint

  sheriff:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.8
        with:
          version: 11.3.0
          cache: true
      - run: pnpm run sheriff
