name: build

on:
  push:
    branches:
      - 'main'
      - '**'

permissions:
  contents: read

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v7
     - name: checkout
       uses: pnpm/action-setup@v6.0.8
       with:
         version: 11.4.0
         cache: true

  build:
    needs: pre
    if: '!cancelled()'
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
        with:
          install: 'true'
      - run: pnpm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: pnpm run test

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: pnpm run lint

  sheriff:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: pnpm run sheriff
