name: build

on:
  push:
    branches:
      - 'main'
      - '**'

permissions:
  contents: read

jobs:
  build:
    if: '!cancelled()'
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
        with:
          install: 'true'
      - run: pnpm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: pnpm run test

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: pnpm run lint

  sheriff:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: pnpm run sheriff
